# Generated by Django 3.2.8 on 2022-10-21 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=500)),
                ('l_name', models.CharField(max_length=30)),
                ('picture', models.ImageField(upload_to='')),
                ('username', models.CharField(max_length=30)),
                ('emailed', models.CharField(max_length=30)),
                ('pwd', models.CharField(max_length=30)),
                ('cnf_pwd', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=500)),
                ('l_name', models.CharField(max_length=30)),
                ('picture', models.ImageField(upload_to='')),
                ('username', models.CharField(max_length=30)),
                ('emailed', models.CharField(max_length=30)),
                ('pwd', models.CharField(max_length=30)),
                ('cnf_pwd', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
            ],
        ),
    ]
